keys:
  - &murderbot
    age1s90xwvtqw9at892s8tyde9lp8vu3rs2lde7pwh7hayuc2sahmv6qmkwpff

creation_rules:
  - path_regex: .*\.(auto\.)?tfvars(\.enc)?$
    key_groups:
      - age:
          - *murderbot

  - path_regex: ./.*/*.json
    key_groups:
      - age:
          - *murderbot

stores:
  yaml:
    indent: 2
  json:
    indent: 2
